name: Scheduled weekly deploy
"on":
  schedule:
    - cron: "0 4 * * *" # every day at 4 AM UTC
  workflow_dispatch:
jobs:
  trigger_netlify_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Trigger Netlify build on latest tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          curl -s -X POST "${{ secrets.NETLIFY_BUILD_HOOK }}?trigger_branch=${LATEST_TAG}"
